name: CI - Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: anglicankenya
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, pdo, pdo_mysql
        coverage: none

    - name: Validate composer.json
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Wait for MySQL
      run: sleep 10

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --testdox
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: anglicankenya
        DB_USERNAME: root
        DB_PASSWORD: root

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: phpcs

    - name: Run PHP CodeSniffer
      run: phpcs --standard=PSR12 --ignore=vendor/ .
      continue-on-error: true